sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: run tests
      script:
      - docker-compose run test ./gradlew clean test
      - docker-compose run test ./gradlew integrationTest
    - stage: build
      script: docker-compose run test ./gradlew bootRepackage

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - sh travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “master” && sh travis/deploy_heroku.sh
