sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: run tests
      script:
        - docker-compose run test ./gradlew clean test
        - docker-compose run test ./gradlew integrationTest
    - stage: build
      script: docker-compose run test ./gradlew bootRepackage
    - stage: generate and upload test coverage
      script:
        - ./gradlew jacocoTestReport
        - bash <(curl -s https://codecov.io/bash)
    - stage: upload image and deploy to heroku
      script:
        - sh travis/deploy_dockerhub.sh
        - test “$TRAVIS_BRANCH” = “master” && sh travis/deploy_heroku.sh
