sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew clean test
  - ./gradlew integrationTest
  - ./gradlew bootRepackage

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - sh travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “master” && sh travis/deploy_heroku.sh
